feat: Add  `exec` CLI command to simplify executing scripts (#135)
- Add `git hooks exec` command to launch executables and run configuration the
  same as Githooks executes when run normally. This features simplifies
  executing add-on scripts/executables distributed in shared hook repositories 
  (and also locally with `ns:gh-self`).

  For example execute the following
  [add-on 'format-all' script](https://github.com/gabyx/Githooks-Docs/blob/main/githooks/scripts/format-docs-all.yaml)
  with:

  ```shell
  git hooks exec --containerized \
    ns:githooks-docs/scripts/format-docs-all.yaml -- \
    --force \
    --dir ./
  ```

  This will launch the specified container and run the script.

  **Note**: You need to have configured this shared repository inside 
  your repo where you use Githooks.

diff --git a/.githooks/pre-commit/cli-docs-up-to-date b/.githooks/pre-commit/cli-docs-up-to-date
--- a/.githooks/pre-commit/cli-docs-up-to-date
+++ b/.githooks/pre-commit/cli-docs-up-to-date
@@ -15,33 +15,34 @@ repoDir="$DIR/../.."
 cd "$repoDir" || exit 1
 
 if command -v "gstat" &>/dev/null; then
-    statCmd="gstat"
+  statCmd="gstat"
 else
-    statCmd="stat"
+  statCmd="stat"
 fi
 
 for file in $STAGED_FILES; do
-    if echo "$file" | grep -qE '^.*/cmd/.*\.go$'; then
+  if echo "$file" | grep -qE '^.*/cmd/.*\.go$'; then
 
-        docDate=$("$statCmd" -c %X "$repoDir/docs/cli/git_hooks.md")
+    docDate=$("$statCmd" -c %X "$repoDir/docs/cli/git_hooks.md")
 
-        if [ "$((docDate + 2 * 5))" -lt "$(date +%s)" ]; then
-            if [ "$autoRegenerate" = "true" ]; then
-                # shellcheck disable=SC2015
-                cd githooks && "scripts/build-doc.sh" || {
-                    echo "! Doc regeneration failed!" >&2
-                    exit 1
-                }
+    # Check if 7 minutes are passed.
+    if [ "$((docDate + 7 * 60))" -lt "$(date +%s)" ]; then
+      if [ "$autoRegenerate" = "true" ]; then
+        # shellcheck disable=SC2015
+        cd githooks && "scripts/build-doc.sh" || {
+          echo "! Doc regeneration failed!" >&2
+          exit 1
+        }
 
-                git add "$repoDir/docs/cli/"*
+        git add "$repoDir/docs/cli/"*
 
-                echo "Docs regenerated." >&2
-            else
-                echo "! You need to regenerate the CLI docs (its too old)!" >&2
-                exit 1
-            fi
-        fi
+        echo "* Docs regenerated." >&2
+      else
+        echo "! You need to regenerate the CLI docs (its too old)!" >&2
+        exit 1
+      fi
     fi
+  fi
 done
 
 echo "* CLI docs is up to date" >&2
